[package]
name = "cdaq-scope"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["clock"] }
eframe = "0.27"
egui_plot = "0.27"
egui_extras = "0.27"     # <-- add this
libloading = "0.8"
serialport = "4"
csv = "1.3.1"
